name: Generate Docker Tags
description: Build release tags (<version>, <YYYY-Qn>, latest) or branch tag.

inputs:
  image:
    description: Full image name, e.g. usdotjpoode/jpo-ode
    required: true

outputs:
  tag_list:
    description: Comma-separated Docker tag list
    value: ${{ steps.out.outputs.tags }}

runs:
  using: composite
  steps:
    - id: ver       # semantic version from tag only
      shell: bash
      run: |
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          NEW_VER="${GITHUB_REF_NAME##*-}"          # jpo-ode-4.2.0 → 4.2.0
        else
          NEW_VER=""                                # no version on non-tag builds
        fi
        echo "new=$NEW_VER" >>"$GITHUB_OUTPUT"

    - id: yq        # resolve YYYY-Qn
      shell: bash
      run: |
        norm() { echo "${1,,}" | sed 's/-/-Q/' | tr '[:lower:]' '[:upper:]'; }
        YQ=''
        if [[ "$GITHUB_REF" == refs/heads/release/* ]]; then
          BR="${GITHUB_REF_NAME##release/}"
          [[ "$BR" =~ ^20[0-9]{2}-q[1-4]$ ]] && YQ="$(norm "$BR")"
        fi
        if [[ -z "$YQ" && ( "$GITHUB_REF_NAME" == master || "$GITHUB_REF" == refs/tags/* ) ]]; then
          mapfile -t rels < <(git for-each-ref --format='%(refname:short)' refs/remotes/origin/release)
          for rb in "${rels[@]}"; do
            git merge-base --is-ancestor "$rb" HEAD 2>/dev/null || continue
            BR="${rb#origin/release/}"
            [[ "$BR" =~ ^20[0-9]{2}-q[1-4]$ ]] || continue
            CAND="$(norm "$BR")"
            [[ -z "$YQ" || "$CAND" > "$YQ" ]] && YQ="$CAND"
          done
        fi
        [[ -n "$YQ" ]] || { echo "::error::No release/YYYY-qN branch found"; exit 1; }
        echo "yq=$YQ" >>"$GITHUB_OUTPUT"

    - id: build    # assemble the final list
      shell: bash
      run: |
        IMAGE="${{ inputs.image }}"
        if [[ -n "${{ steps.ver.outputs.new }}" ]]; then
          TAGS="$IMAGE:${{ steps.ver.outputs.new }},$IMAGE:${{ steps.yq.outputs.yq }},$IMAGE:latest"
        elif [[ "$GITHUB_REF_NAME" == master ]]; then
          echo "::error::Master push must be tagged"; exit 1
        else
          TAGS="$IMAGE:${GITHUB_REF_NAME//\//-}"
        fi
        echo "tags=$TAGS" >>"$GITHUB_OUTPUT"

    - id: out      # surface the tag list
      shell: bash
      run: echo "::set-output name=tags::${{ steps.build.outputs.tags }}"
