name: Docker build

on:
  workflow_call:
    inputs:
      context:
        default: .
        type: string
      file:
        default: Dockerfile
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: docker/setup-buildx-action@v3

      - id: meta
        uses: usdot-jpo-ode/actions/build-metadata@main

      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: false
          build-args: |
            BUILD_DATE=${{ steps.meta.outputs.build_date }}
            VCS_REF=${{ steps.meta.outputs.vcs_ref }}
            VERSION=${{ steps.meta.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
