name: Docker build

on:
  workflow_call:
    inputs:
      context:
        type: string
        default: '.'
      file:
        type: string
        default: 'Dockerfile'
      build-args:
        type: string
        default: ''
    secrets:
      MAVEN_GITHUB_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: meta
        name: Generate build metadata
        uses: usdot-jpo-ode/actions/build-metadata@main

      - name: Docker Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: false
          build-args: |
            BUILD_DATE=${{ steps.meta.outputs.build_date }}
            VCS_REF=${{ steps.meta.outputs.vcs_ref }}
            VERSION=${{ steps.meta.outputs.version }}
            ${{ inputs.build-args }}
          secrets: |
            MAVEN_GITHUB_TOKEN=${{ secrets.MAVEN_GITHUB_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
