name: Build & push Docker image

on:
  workflow_call:
    inputs:
      image:          
        required: true
        type: string
      context:
        required: false
        type: string
        default: '.'
      file:
        required: false
        type: string
        default: 'Dockerfile'
      build-args:
        required: false
        type: string
        default: ''
      secrets:
        required: false
        type: string
        default: ''
    secrets:
      DOCKERHUB_USERNAME: { required: true }
      DOCKERHUB_TOKEN:    { required: true }
      MAVEN_GITHUB_TOKEN: { required: false }

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all release branches
        run: |
          git fetch origin 'refs/heads/release/*:refs/remotes/origin/release/*'

      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: meta
        uses: usdot-jpo-ode/actions/build-metadata@main

      - id: tags
        uses: usdot-jpo-ode/actions/generate-tags@main
        with:
          image: ${{ inputs.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: true
          tags: ${{ steps.tags.outputs.tag_list }}
          build-args: |
            BUILD_DATE=${{ steps.meta.outputs.build_date }}
            VCS_REF=${{ steps.meta.outputs.vcs_ref }}
            VERSION=${{ steps.meta.outputs.version }}
            ${{ inputs.build-args }}
          secrets: |
            MAVEN_GITHUB_TOKEN=${{ secrets.MAVEN_GITHUB_TOKEN }}
            ${{ inputs.secrets }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
