name: Build & push Docker image
on:
  workflow_call:
    inputs:
      image:          
        required: true
        type: string
      version_file:   
        default: VERSION
        type: string
    secrets:
      DOCKERHUB_USERNAME: { required: true }
      DOCKERHUB_TOKEN:   { required: true }
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: meta
        uses: usdot-jpo-ode/actions/build-metadata@main 

      - name: Determine Docker organization and tag
        id: tags
        uses: usdot-jpo-ode/actions/generate-tags@main
        with:
          image: ${{inputs.image}}
          version_file: ${{inputs.version_file}}

      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          build-args: |
            BUILD_DATE=${{ steps.meta.outputs.build_date }}
            VCS_REF=${{ steps.meta.outputs.vcs_ref }}
            VERSION=${{ steps.meta.outputs.version }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max
